package com.cydeo.entity;

import com.cydeo.enums.Gender;
import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

@Entity                     // create table
@Table(name = "students")   // give table name
public class Student {

    @Id                     // assign primary id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // id generated by database manager
    private int id;
    @Column(name = "studentFirstName")// change name
    private String firstName;
    @Column(name = "studentLastName")  // change name
    private String lastName;
    private String email;

    @Transient   // doesn't create column with this field
    private String city;

    @Column(columnDefinition = "DATE")
    private LocalDate birthdate;
    @Column(columnDefinition = "TIME")
    private LocalTime birthtime;
    @Column(columnDefinition = "TIMESTAMP")
    private LocalDateTime birthdatetime;
    @Enumerated(EnumType.STRING)
    private Gender gender;

}
